### ISSUE TITLE
Home Page 

### ISSUE THREAD

**Issue by utkarsh0702** [sushamaborhade/Liber#6]

**Comment by savagecarol** [comment]
what is the problem in home page describe it
i want to work on it.

**Comment by utkarsh0702** [comment]
@savagecarol The problem with the home screen has been resolved. Only the pr has not opened. 
The issue is been resolved.
If you don't mind can you work on firebase authentication and storage? If you are ready I will assign you the issue.

**Comment by savagecarol** [comment]
okay cool

**Comment by savagecarol** [comment]
assign me firebase part

**Comment by utkarsh0702** [comment]
@savagecarol please comment on the issue #5
